name: anvio-test-python
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python=3.10
- sqlite
- prodigal
- idba
- mcl
- muscle
- hmmer
- diamond
- blast
- megahit
- spades
- bowtie2
- bwa
- graphviz
- samtools
- trimal
- iqtree
- trnascan-se
- fasttree
- vmatch
- r-base
- r-tidyverse
- r-optparse
- r-stringi
- r-magrittr
- bioconductor-qvalue
- fastani
