{% set version = "7.1_dev" %}

package:
  name: anvio
  version: {{ version }}

build:
  noarch: generic
  number: 0

requirements:
  run:
    - anvio-minimal =={{ version }}
    - prodigal
    - mcl
    - muscle
    - hmmer
    - diamond
    - blast
    - megahit
    - spades
    - bowtie2
    - bwa
    - samtools
    - centrifuge
    - trimal
    - iqtree
    - fastani
    - trnascan-se
    - r-base
    - r-stringi
    - r-tidyverse
    - r-magrittr
    - r-optparse
    - bioconductor-qvalue
    - fasttree
    - vmatch

test:
  commands:
    - anvi-self-test --help

about:
  home: http://merenlab.org/software/anvio/
  license: GPL-3.0-or-later
  license_family: GPL3
  summary: "An interactive analysis and visualization platform for 'omics data"
  dev_url:  https://github.com/merenlab/anvio

extra:
  container:
    # extended-base generates en_US.UTF-8 locale and sets LC_ALL, LANG properly
    extended-base: True
