name: Daily Component Tests and Migrations

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    name: Daily Component Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
      fail-fast: false
    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: 'latest'
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,bioconda
        activate-environment: anvio_env
    - name: "Set up the conda environment"
      shell: bash -l {0}
      run: |
        conda info -a
        conda install -y "mamba >=0.24.0"
        mamba env create -f .conda/environment.yaml
    - uses: actions/checkout@v2
    - name: "Install anvi'o from the codebase"
      shell: bash -l {0}
      run: |
        pip install .
    - name: "Run component tests for general metagenomics tasks"
      shell: bash -l {0}
      run: |
        anvi-self-test --suite metagenomics-full --no-interactive
    - name: "Run component tests for metabolism framework"
      shell: bash -l {0}
      run: |
        anvi-self-test --suite metabolism --no-interactive
# the following causes our actions to fail due to space limitations :/
# please do not uncomment this until we have a solution.
    #- name: "Migrate ancient anvi'o databases"
    #  shell: bash -l {0}
    #  run: |
    #    anvi-self-test --suite database-migrations
